use super::*;

const PI: fixed32 = crate::fixed::PI;
const ZERO: fixed32 = crate::fixed::ZERO;
const ONE: fixed32 = crate::fixed::ONE;
const TWO: fixed32 = crate::fixed::TWO;

pub struct BackendConfig {
    /// Number of expected symbols per seconds
    pub symbol_rate: fixed32,

    /// Number of samples per seconds
    pub sample_rate: fixed32,

    /// Gain of the proportional factor of the PLL used to learn the symbol rate
    pub symbol_pll_p_gain: fixed32,

    /// Gain of the integral factor of the PLL used to learn the symbol rate
    pub symbol_pll_i_gain: fixed32,

    /// Decimation factor of the frontend
    pub decimation: usize,
}

#[allow(non_snake_case)]
pub struct BackendDBPSK {
    sample_rate: fixed32,

    /// Number of expected symbols per seconds
    symbol_rate0: fixed32,

    /// Current estimation of the number of symbols per seconds
    symbol_rate: fixed32,

    /// Phase of the symbol clock
    symbol_phase: fixed32,

    /// Last observed state, used by to compute the difference between consecutive states
    last_state: bool,

    /// Integral of the errors of the symbol phase
    symbol_error_integral: fixed32,

    /// Gain of the proportional factor of the PLL used to learn the symbol rate
    symbol_pll_p_gain: fixed32,

    /// Gain of the integral factor of the PLL used to learn the symbol rate
    symbol_pll_i_gain: fixed32,

    /// Last observed in-phase value, used to detect zero crossings and learn the symbol rate
    pub last_I: fixed32,

    /// Last observed quadrature value
    pub last_Q: fixed32,

    /// Decimation factor of the frontend
    decimation: usize,
}

impl BackendDBPSK {
    pub fn new(config: BackendConfig) -> BackendDBPSK {
        return Self{
            sample_rate: config.sample_rate,
            symbol_rate0: config.symbol_rate,
            symbol_rate: config.symbol_rate,
            symbol_pll_p_gain: config.symbol_pll_p_gain,
            symbol_pll_i_gain: config.symbol_pll_i_gain,
            decimation: config.decimation,
            symbol_error_integral: ZERO,
            symbol_phase: ZERO,
            last_state: false,
            last_I: ZERO,
            last_Q: ZERO,
        };
    }
}

fn fmodulo(mut x: fixed32, y: fixed32) -> fixed32 {
    while x > y/TWO { x -= y; }
    while x < -y/TWO { x += y; }
    return x;
}

impl Backend for BackendDBPSK {
    /// Use the symbols `0` and `1` to represent input bits, `-1` is used to represent an unexpected
    /// event (the phase is smaller or bigger than expected during a zero crossing)
    type Symbol = i8;

    #[allow(non_snake_case)]
    fn run(&mut self, I: fixed32, Q: fixed32) -> BackendOutput<i8> {
        let mut output = BackendOutput{
            carrier_error: None,
            symbol: None,
        };

        let prev_symbol_phase = self.symbol_phase;
        self.symbol_phase += TWO * PI * fixed32::from(self.decimation) *
            (self.symbol_rate / self.sample_rate);
        while self.symbol_phase > TWO*PI { self.symbol_phase -= TWO*PI; }

        if prev_symbol_phase <= PI && self.symbol_phase > PI {
            // The current symbol is the difference between the current and previous state
            output.symbol = Some(if (I > ZERO) == self.last_state { 0 } else { 1 });
            self.last_state = I > ZERO;

            // Learn the angle of the carrier generated by the frontend
            let theta: fixed32 = fixed32::atan2(Q, I);
            let error = - fmodulo(theta, PI);
            output.carrier_error = Some(error);
        }

        // Zero crossing detection: we try to minimise the symbol phase at this instant using a PLL
        if (self.last_I < ZERO && I >= ZERO) || (self.last_I >= ZERO && I < ZERO) {
            let error = - fmodulo(self.symbol_phase, TWO * PI);
            self.symbol_error_integral += self.symbol_pll_i_gain * error;

            let factor =
                ONE + self.symbol_pll_p_gain * error + self.symbol_error_integral;
            self.symbol_rate = self.symbol_rate0 * factor;

            let unexpected =
                fixed32::from(0.5) * PI < self.symbol_phase &&
                self.symbol_phase < fixed32::from(1.5) * PI;

            if unexpected { output.symbol = Some(-1); }
        }

        self.last_I = I;
        return output;
    }
}
